version: '3'
services:
  mysql_teste:
    image: mysql:5.7.22
    container_name: mysql_teste
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./data.sql:/data.sql
